KPIV-34: end the call if pivot has trouble with HTTP Url in subsequent requests
2600hz/kazoo-pivot pull request #31
Opened 2024-05-08 12:36 UTC by dhuynh-Kazoo

If the initial request to web server fails for any reason because the cf_pivot is still up and waiting for pivot, `publish_failed` will work as before and causes `cf_pivot` app to continue to next action in callflow if any as before.

But after processing the initial TwiML response from web server, if it commands to Redirect or needs to call back an action, if this subsequent HTTP request to web server fails for any reason, the pivot sens publish_failed and stops but the call stays up because cf_pivot is not up anymore and nothing in callflow side listening for this event.

This fixes the issue by hanging up the call if HTTP request for subsequent request failed. 

Example XML:

```xml
<Response>
    <Redirect method="GET">http://localhost/give_me_another_twiml.php</Redirect>
</Response>
```

With Gather, actionUrl could  not reach:

```xml
<Response>
    <Gather method="GET" action="http://localhost/give_me_another_twiml.php"></Gather>
</Response>

```

2024-05-08 15:53 UTC, icehess commented on src/pivot_call.erl
> +    kapps_call_command:hangup(Call),
@dhuynh-Kazoo As we discussed it before this doesn't consider that this is the initial request to web server or if this is result of subsequent action or redirect action.

For the initial we still want to stop and send publish_failed to `cf_pivot` to let it handle it from there, but for subsequent requests we can stop and issue the hangup command right here since no one is listening for `publish_failed` anymore to continue or hangup.

2024-05-10 08:25 UTC, dhuynh-Kazoo commented on src/pivot_call.erl
> +    kapps_call_command:hangup(Call),
hi @icehess, I double-checked the _publish_failed/2_, it is called for every http request failed, and it does not distinguish the first vs following requests.  Any HTTP failed will trigger that function.

https://github.com/2600hz/kazoo-pivot/blob/d19fcc8630cf6cb77a957b1c888ea34a5ca5c65b/src/pivot_call.erl#L326
https://github.com/2600hz/kazoo-pivot/blob/d19fcc8630cf6cb77a957b1c888ea34a5ca5c65b/src/pivot_call.erl#L379
https://github.com/2600hz/kazoo-pivot/blob/d19fcc8630cf6cb77a957b1c888ea34a5ca5c65b/src/pivot_call.erl#L391

So I think we can ensure that if failed request, cf_pivot always receives the `{<<"pivot">>,<<"failed">>}` 

I ran 3 tests for URL not found, server error, and client error -> they all send  `{<<"pivot">>,<<"failed">>}`  to cf_pivot and terminate this process

2024-05-10 16:11 UTC, icehess requested changes

2024-05-10 16:11 UTC, icehess commented on src/pivot_call.erl
> +                  timer:sleep(?MILLISECONDS_IN_SECOND/10),
What you are doing doing here is achievable by just `erlang:send_after(?MILLISECONDS_IN_SECOND, Srv, {'stop', Call})`.

In any case I don't understand why is this? Yes there is a race condition between receiving `DOWN` and `{stop, Call}` message, stop is probably received first and `pivot_call` process goes down before receiving `DOWN`, but so what? both processes go down eventually perfectly fine. (with the `is_process_alive` in `terminate` it is even smoother)

2024-05-10 16:11 UTC, icehess commented on src/pivot_call.erl
> +    kapps_call_command:hangup(Call),
better to not `publish_failed` if the initial call iteration is bigger than current call iteration. But that is for not bothering a message which is not going to be received/process by any other process.

The real fix is when stopping pivot_call process because of http_error, if the initial call iteration is bigger than current call iteration it needs to hangup the call before stopping.

you may store initial call iteration in the `Call` itself for easier access for both pivot_call and response process.

2024-05-10 16:20 UTC, icehess commented on src/pivot_call.erl
> +                  timer:sleep(?MILLISECONDS_IN_SECOND/10),
oops sorry, that send_after works if you do `gen_listener:call` to `{stop, call}`.

2024-05-10 16:40 UTC, dhuynh-Kazoo commented on src/pivot_call.erl
> +                  timer:sleep(?MILLISECONDS_IN_SECOND/10),
Hi @icehess, I just would like to make the flow clear. I also saw that's fine and actually no need to adding code.

My idea when solving the race conditions to correct response_pid and response_ref. We can remove first terminate/2 func (I have to double check that) because terminate when handle_resp dead, these above fields always become undefined, always go to second terminate/2

2024-05-15 13:23 UTC, icehess requested changes

2024-05-15 13:23 UTC, icehess commented on src/pivot_call.erl
> +    ok.
```suggestion
    erlang:send_after(?MILLISECONDS_IN_SECOND, Srv, {'stop', Call}).
```

2024-05-15 13:23 UTC, icehess commented on src/pivot_call.erl
> +maybe_hangup_call(Call, 'true') ->
I don't understand what `is_redirect` is being used here. It seems useless, next clause is exactly what you want to do with simpler logic, it hangup either because of redirect or any other reason the translator made another `new_request`. Let's remove this `is_redirect`.

2024-05-15 13:23 UTC, icehess commented on src/pivot_call.erl
> +maybe_clear_redirect('true') -> 'false';
remove this and `is_redirect` codes.

2024-05-15 13:23 UTC, icehess commented on src/pivot_call.erl
> +            maybe_publish_failed(Call, RequesterQ),
Also call maybe_hangup_call here.

2024-05-15 13:34 UTC, dhuynh-Kazoo commented on src/pivot_call.erl
> +maybe_hangup_call(Call, 'true') ->
Thank you @icehess, I removed it in my local because it does not have any values but it has not been pushed yet, going to push again now

2024-05-15 15:43 UTC, icehess requested changes

2024-05-15 15:43 UTC, icehess commented on src/pivot_call.erl
> +    end.
I think using `not` here makes the condition less direct and less readable, and maybe even missed by reader. Try match the condition you want directly and avoid ambiguity:
 
```suggestion
    case is_first_pivot_request(Call) of
        'true' -> 'ok';
        'false' -> kapps_call_command:hangup(Call)
    end.
```

2024-05-15 15:43 UTC, icehess commented on src/pivot_call.erl
> +            'skip'
```suggestion
            'ok'
```

2024-05-28 23:39 UTC, icehess approved these changes

2024-05-28 23:40 UTC, merged